package GUI.Dialog;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class DialogChoose extends javax.swing.JDialog {

    private ArrayList<String> data;
    private String query;
    private final Callback callback;
    private final DefaultTableModel tableModel;

    public DialogChoose(java.awt.Frame parent, boolean modal, String description, Callback callback) {
        super(parent, modal);
        initComponents();
        lblDescription.setText(description);

        this.tableModel = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Tên"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        table.setModel(this.tableModel);

        setLocationRelativeTo(parent);
        this.callback = callback;
        this.data = new ArrayList<>();
        this.query = "";

        this.data = this.callback.getList(query);
        displayList(this.query, this.data);
    }

    private void displayList(String query, ArrayList<String> list) {
        tableModel.setRowCount(0);
        if (query.isEmpty()) {
            tableModel.addRow(new Object[]{"Tất cả"});
        }
        for (String s : list) {
            Object[] row = {s};
            tableModel.addRow(row);
        }
    }

    public static abstract class Callback {

        public Callback() {
        }

        public abstract ArrayList<String> getList(String query);

        public abstract void handleConfirm(String selectedValue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pContainer = new javax.swing.JPanel();
        pInput = new javax.swing.JPanel();
        lblDescription = new javax.swing.JLabel();
        pSearch = new javax.swing.JPanel();
        txtInput = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        pTable = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        pBtnConfirm = new javax.swing.JPanel();
        btnConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý thành viên");
        setResizable(false);

        pContainer.setBackground(new java.awt.Color(240, 247, 250));
        pContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pContainer.setLayout(new java.awt.BorderLayout(10, 10));

        pInput.setBackground(new java.awt.Color(240, 247, 250));
        pInput.setLayout(new java.awt.BorderLayout(0, 5));

        lblDescription.setText("[description]");
        pInput.add(lblDescription, java.awt.BorderLayout.NORTH);

        pSearch.setBackground(new java.awt.Color(240, 247, 250));
        pSearch.setLayout(new java.awt.BorderLayout(10, 0));

        txtInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInputKeyPressed(evt);
            }
        });
        pSearch.add(txtInput, java.awt.BorderLayout.CENTER);

        btnSearch.setText("Tìm kiếm");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        pSearch.add(btnSearch, java.awt.BorderLayout.EAST);

        pInput.add(pSearch, java.awt.BorderLayout.CENTER);

        pContainer.add(pInput, java.awt.BorderLayout.NORTH);

        pTable.setLayout(new java.awt.BorderLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
        }

        pTable.add(scrollPane, java.awt.BorderLayout.CENTER);

        pContainer.add(pTable, java.awt.BorderLayout.CENTER);

        pBtnConfirm.setBackground(new java.awt.Color(240, 247, 250));
        pBtnConfirm.setLayout(new java.awt.BorderLayout());

        btnConfirm.setText("OK");
        btnConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        pBtnConfirm.add(btnConfirm, java.awt.BorderLayout.EAST);

        pContainer.add(pBtnConfirm, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if (txtInput.getText().trim().toLowerCase().equals(query.toLowerCase())) {
            return;
        }
        query = txtInput.getText().trim();
        data = callback.getList(query);
        displayList(query, data);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtInput.getText().trim().toLowerCase().equals(query.toLowerCase())) {
                return;
            }
            query = txtInput.getText().trim();
            data = callback.getList(query);
            displayList(query, data);
        }
    }//GEN-LAST:event_txtInputKeyPressed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:+
        int row = table.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn");
            return;
        }
        String selectedValue = table.getModel().getValueAt(row, 0).toString();
        String value = selectedValue.equalsIgnoreCase("Tất cả") ? "" : selectedValue;
        this.callback.handleConfirm(value);
        this.dispose();
    }//GEN-LAST:event_btnConfirmActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JPanel pBtnConfirm;
    private javax.swing.JPanel pContainer;
    private javax.swing.JPanel pInput;
    private javax.swing.JPanel pSearch;
    private javax.swing.JPanel pTable;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
